consultation01/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
]

consultation01/shopapp/urls.py
from django.urls import path

from .views import shop_index, products_list, orders_list

app_name = "shopapp"

urlpatterns = [
    path("", shop_index, name="index"),
    path("products/", products_list, name="products-list"),
    path("orders/", orders_list, name="orders-list"),
]

consultation01/shopapp/models.py
from typing import TYPE_CHECKING

from django.contrib.auth.models import User
from django.db import models


class Product(models.Model):
    class Meta:
        ordering = ["-name"]
        verbose_name_plural = "products"

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=False)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"Product(pk={self.pk}, name={self.name!r})"


class Order(models.Model):
    delivery_address = models.TextField(null=False, blank=True)
    promocode = models.CharField(max_length=30, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")

consultation01/shopapp/views.py
from django.http import HttpRequest
from django.shortcuts import render

from shopapp.models import Product, Order


def shop_index(request: HttpRequest):
    return render(request, 'shopapp/index.html')


def products_list(request: HttpRequest):
    context = {
        "products": Product.objects.all(),
    }
    return render(request, 'shopapp/products-list.html', context=context)


def orders_list(request: HttpRequest):
    context = {
        "orders": Order.objects.select_related("user").prefetch_related("products").all(),
    }
    return render(request, 'shopapp/orders-list.html', context=context)

consultation01/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}

    {% endblock %}
  </title>
</head>
<body>
{% block body %}

{% endblock %}

<div>
  Page load time: {% now 'H:i' %}
</div>
<div>
  {% now "l" as current_day_of_week %}
  Today is {{ current_day_of_week }}
</div>
</body>
</html>

consultation01/shopapp/templates/shopapp/index.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Shop index
{% endblock %}


{% block body %}
  <h1>Pages:</h1>
  <h3><a href="{% url 'shopapp:products-list' %}">Products</a></h3>
  <h3><a href="{% url 'shopapp:orders-list' %}">Orders</a></h3>
{% endblock %}

consultation01/shopapp/templates/shopapp/orders-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  <div>
    {% for order in orders %}
      <p>Order by {% firstof order.user.first_name order.user.username %}</p>
      <p>Order to {{ order.delivery_address }}</p>
      <p>Promocode: <code>{{ order.promocode }}</code></p>
      <div>
        Products in order:
        <ul>
          {% for product in order.products.all %}
            <li>#{{ product.id }}. {{ product.name }}</li>
          {% endfor %}
        </ul>
      </div>
    {% endfor %}
  </div>
{% endblock %}

consultation01/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Products list
{% endblock %}

{% block body %}
  <h1>Products:</h1>
  <div>
    {% for product in products %}
      <div>
        <p>Name: <strong>{{ product.name }}</strong></p>
        <p>Price: ${{ product.price }}</p>
        <p>Discount: {% firstof product.dicsount 'no discount'  %}</p>
      </div>
    {% endfor %}
  </div>
{% endblock %}